#基础设置
server:
  port: 8090
  servlet:
    context-path: /jimfly-bake

spring:
  #数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bake?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Jeff9302132
    driver-class-name: com.mysql.cj.jdbc.Driver
  #页面
  thymeleaf:
    cache: false
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  #redis
  redis:
    database: 7
    host: 127.0.0.1
    port: 6379
    password: jimfly951013
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
        #最大连接数，负数表示没有限制
        max-active: 200
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  #程序
  application:
    name: jimfly-bake




#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:com/jimfly/bake/dao/*/*.xml
  global-config:
    db-config:
      db-type: mysql



#日志
logging:
  level:
    root: error
    org:
      springframework:
        web: debug
    com:
      jimfly:
        bake: error